#!/bin/bash

# wrapper fallback
if [[ $@ =~ ^--sc|\ --sc\ |--sc$ ]];
then echo '' --sc: implies -dils --time-style=long-iso .. 1>&2
else exec /bin/ls $*
fi

# remove -l from switches
#>! fixme: this still excludes --long opts
AnL=''; for ARG in $*; do
    AnL="$AnL `echo $ARG | perl -ne '
    if (/^-/ and not /^--/) {s/l//g and print qq{$_}}
    elsif (not /^--sc$/) {print}'`";
done; echo '' -ARGS:$AnL 1>&2

# separate swithes OPTS & files-specs ARGS
O=''; A=''


# foreach file-spec/*, list CAT/s rec/s
/bin/ls -1 $AnL | while read F; do
    S=${F##*/}; echo '' -$S: 1>&2
    ls -dils --time-style=long-iso "$F"
    if ! [[ -d $F ]]
    then        
        mount | perl -ne 'm{^/.* on (.*) type } and print "$1\n"' | while read FS; do
            cd $FS 2>/dev/null
            export CAT=`ls -1t *@*.sqlite | head -1`
            sqlite3 $CAT "
                      SELECT inode,du,perms,lns,ug,s,mtime,dir,fn
                      FROM find_printf
                      WHERE fn = '$S'
                      LIMIT 10" \
                  | perl -nle '
                      @A=split (/\|/);
                      $ENV{"CAT"} =~ /(.*)@([^.,]+)[.,]/;
                      print join (" ",@A[0..3]).qq{ $1 $2 }.join (" ",@A[5..$#A-1])."$A[$#A]"'
        done
    fi
done
