#!/bin/bash
# remove -l from switches

if [[ $@ =~ ^--sc|\ --sc\ |--sc$ ]];
then echo '' --sc: implies -l.. 1>&2
else exec /bin/ls $*
fi

A=''; for ARG in $*; do
    A="$A `echo $ARG | perl -ne '
    if (/^-/ and not /^--/) {s/l//g and print qq{$_}}
    elsif (not /^--sc$/) {print}'`";
done; echo '' -ARGS:$A 1>&2

/bin/ls $A -1 | while read F; do
    S=${F##*/}; echo '' -S:$S 1>&2
    mount | perl -ne 'm{^/.* on (.*) type } and print "$1\n"' | while read FS; do
        cd $FS 2>/dev/null
        CAT=`ls -1t *@*.sqlite | head -1`
        export CAT
        sqlite3 $CAT "
        SELECT * FROM find_printf
        WHERE fn = '$S'
        LIMIT 10" \
            | perl -nle '
              @A=split (/\|/); @A=@A[2..$#A];
              $ENV{"CAT"} =~ /(.*)@([^.,]+)[.,]/;
              print join (" ",@A[0..3]).qq{ $1 $2 }.join (" ",@A[5..$#A-1])."$A[$#A]"'
    done
done
