#!/bin/bash
#>! move perl -pe 's/([\d-]+\s+[\d:]+)\.\d+/$1/') from sclocate-import to here
function find_act \
    { find "$1" -xdev -type f -printf "%i %k %M %n %u %g %s %TY-%Tm-%Td %TH:%TM:%TS %h/%f\n"
    true; }


function find_cats \
    { mount | perl -ne 'm{^/.* on (.*) type } and print "$1\n"' | while read FS; do
        cd $FS; ls -1dht `pwd`/*@*[0-9].sqlite | head -1
    done; }


# list files with equal sizes
# IN/s: < [[find_cats]]
function list_sdups \
    { while read CAT; do 
        sqlite3 "$CAT" <<-EOF | tail -n+2 | awk -v CAT=$CAT '{print $0,CAT}';
		BEGIN TRANSACTION;
		SELECT ix FROM find_printf f
		CROSS JOIN (SELECT s, count(s) as scnt FROM find_printf WHERE s <> 0 GROUP BY s) sc ON sc.s = f.s
		CROSS JOIN (SELECT fn, count(fn) as ncnt FROM find_printf GROUP BY fn) nc ON nc.fn = f.fn
		ORDER BY scnt DESC, f.fn;
		COMMIT;
		EOF
        # LIMIT 100
        done; }


# EX/s:> find_cats | tun_cat
function tun_cat \
    { while read CAT; do
        case $1 in
            (--ix1 | *) echo 1>&2 '' -tun_cat: 'indexing $CAT: i,s,mt,dir, & fn..'
                sqlite3 "$CAT" <<-EOF
			CREATE INDEX "find_printf_inode" ON find_printf (inode ASC);
			CREATE INDEX "find_printf_s" ON find_printf (s ASC);
			CREATE INDEX "find_printf_mtime" ON find_printf (mtime ASC);
			CREATE INDEX "find_printf_dir" ON find_printf (dir ASC);
			CREATE INDEX "find_printf_fn" ON find_printf (fn ASC);
			CREATE INDEX "find_printf_md5" ON find_printf (md5 ASC);
			EOF
                ls -ldht "$CAT" # `pwd`/*@*.sqlite* `pwd`/$F.sqlite | sort -t@ -k2r -u
                ;;
        esac
        done; }


#>! move this to scatfs iface. (There should be fn-set of ls, cp, mv, locate, & such..)
# EX/s:> sclocate eng.%
function sclocate \
    { find_cats | while read CAT; do
        ls -ldh `dirname $CAT`/*@*.sqlite
        sqlite3 "$CAT" "SELECT * FROM find_printf WHERE fn LIKE '$1' LIMIT 10"
        echo;
    done; }


#>! rewrite whole lib to python
# paginate IN-2 to file to free up origin IN-1
# EX/s:> pgpipe "seq 8" "cat -n"
# EX/s:> pgpipe "find_cats | list_sdups" last_rec
function pgpipe \
    { for i in `seq 0 3 6`
    do
        echo 1>&2 '' -$i..`expr $i + 3 - 1`:
        eval $1 | sed -ne "`expr $i + 1`,`expr $i + 3`p" > /tmp/.pgpipe
        cat /tmp/.pgpipe | eval $2
    done
    true; }


# find last file/'s rec. candidates: - and list them, || update them..
# IN/s: < [[list_sdups]]
# EX/s:> find_cats | list_sdups | last_rec
function last_rec \
    { while read IX CAT; do
        LASTC=$(sqlite3 "$CAT" "
            SELECT inode,du,'-',lns,'-','-',s,mtime,dir,fn
            FROM find_printf f
            WHERE ut IS NULL
            AND dir = (SELECT dir FROM find_printf WHERE ix=$IX)
            AND fn = (SELECT fn FROM find_printf WHERE ix=$IX)
            ORDER BY dt DESC
            LIMIT 1"\
          | perl -nle '
            @A=split /\|/;
            print join (" ",@A[0..$#A-1])."$A[$#A]"')
        S=`echo $LASTC | cut -d\  -f7`
        P=`echo $LASTC | cut -d\  -f10-`
        F=${P##*/}
        if [[ 0 != `echo $LASTC | wc -w` ]]
        then
            LASTF=$(find 2>&1 "`dirname $CAT`/$P" \
                -type f \
                -printf "%i %k - %n - - %s %TY-%Tm-%Td %TH:%TM:%TS %h/%f\n" \
                | perl -pe 's/([\d-]+\s+[\d:]+)\.\d+/$1/')
            if [[ "`echo $LASTC | cut -d\  -f-9`" != "`echo $LASTF | cut -d\  -f-9`" ]];
            then
                echo 1>&2
                echo 1>&2 $IX $CAT: '<>' # -S: $S -F:$F
                echo 1>&2 ' <-'$LASTC
                echo 1>&2 ' ->'$LASTF
                case $1 in
                    (+add | *)
                        echo 1>&2 '' +add/ing: utime-label to $CAT: `dirname $CAT`/$P
                        UT=`date +%Y-%m-%d\ %T`
                        sleep 1
                        sqlite3 "$CAT" <<-EOF
				BEGIN TRANSACTION;
				UPDATE find_printf 
				SET ut = '$UT'
				WHERE ut IS NULL
				AND ix = $IX;
				COMMIT;
				EOF
                        if [[ $LASTF =~ find: ]]
                        then true
                        else 
                            LASTR=$(find_act "`dirname $CAT`/$P" | head -1)
                            echo 1>&2 '' +add/ing: rec to $CAT: $LASTR
                            echo $LASTR | sclocate-import | head #>! sqlite3 "$CAT"
                            ls -ldht "$CAT" # `pwd`/*@*.sqlite* `pwd`/$F.sqlite | sort -t@ -k2r -u
                        fi;;
                esac
            else echo 1>&2 -n .
            fi
        fi
        done; }


##
# original version:
# !/usr/bin/python
# Usage: %s add <CDMountPoint> <CDLabel> <dbfile>
#        %s del <CDLabel> <dbfile>
#        %s help
# ''' % (sys.argv[0],sys.argv[0],sys.argv[0])
